server:  port: 8080
spring:
  kafka:
    consumer:
      group-id: "test-group"
      auto-offset-reset: earliest
      key-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer  application:    name: listener-config,producer-config  cloud:    config:      uri: http://localhost:8888
management:  endpoints:    web:      exposure:        include: refresh